---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sahtoso-columbia
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      run: sahtoso-columbia
  template:
    metadata:
      labels:
        run: sahtoso-columbia
        sahtoso-columbia-version: 'main'
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'
    spec:
      containers:
        - name: frontend
          image: 'eu.gcr.io/akvo-lumen/sahtoso-columbia/frontend:main'
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 64Mi
