name: Build and Push

on:
  workflow_call:
    secrets:
      GIT_ACCESS_TOKEN:
        required: true
    inputs:
      app-name:
        description: 'Application Name'
        required: true
        type: string
      service-name:
        description: 'Service Name'
        required: true
        type: string


jobs:
  process:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Resository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: yarn-artifact
          path: artifact

      - name: Checkout Reusable Workflow
        uses: actions/checkout@v3
        with:
          repository: anjar-org/core-pipeline
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          path: main-github-workflow

      - name: Build
        run: ./main-github-workflow/ci/general/build.sh ${{ inputs.app-name }} ${{ inputs.service-name }} $GITHUB_REF_NAME.$GITHUB_SHA
        shell: bash

      - name: Write secret to file
        run: echo "${{ secrets.GCLOUD_SERVICE_ACCOUNT }}" | base64 --decode > gcp.json
        shell: bash

      - name: Push
        run: ./main-github-workflow/ci/general/push.sh  ${{ inputs.app-name }} ${{ inputs.service-name }} $GITHUB_REF_NAME.$GITHUB_SHA
        shell: bash
