name: Build and Push

on:
  workflow_call:
    secrets:
      GCLOUD_SERVICE_ACCOUNT:
        required: true
    inputs:
      app-name:
        description: 'Application Name'
        required: true
        type: string
      service-name:
        description: 'Service Name'
        required: true
        type: string
      dockerfile-location:
        description: 'Location of Dockerfile'
        required: true
        type: string


jobs:
  process:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Resository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: .

      - name: Checkout Reusable Workflow
        uses: actions/checkout@v3
        with:
          repository: akvo/main-github-workflow
          path: main-github-workflow

      - name: Build
        run: ./main-github-workflow/helpers/general/build.sh ${{ inputs.app-name }} ${{ inputs.service-name }} $GITHUB_REF_NAME.$GITHUB_SHA ${{ inputs.dockerfile-location }}
        shell: bash

      - name: Write secret to file
        run: echo "${{ secrets.GCLOUD_SERVICE_ACCOUNT }}" | base64 --decode > gcp.json
        shell: bash

      - name: Push
        run: ./main-github-workflow/helpers/general/push.sh  ${{ inputs.app-name }} ${{ inputs.service-name }} $GITHUB_REF_NAME.$GITHUB_SHA
        shell: bash
