name: NPM Operation

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node version'
        required: true
        type: string
      npm-command:
        description: 'NPM Command that will be executed'
        required: true
        type: string

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Resository
        uses: actions/checkout@v3

      - name: Checkout Reusable Workflow
        uses: actions/checkout@v3
        with:
          repository: akvo/main-github-workflow
          path: main-github-workflow

      - name: NPM command execution
        run: ./main-github-workflow/helpers/node/npm-operation.sh ${{ inputs.node-version }} "${{ inputs.npm-command }}"
        shell: bash

      - name: NPM Artifact Upload
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: app/npm
          retention-days: 1
