name: Rollout

on:
  workflow_call:
    secrets:
      GCLOUD_SERVICE_ACCOUNT:
        required: true
    inputs:
      app-name:
        description: 'Application Name'
        required: true
        type: string
      service-name:
        description: 'Service Name'
        required: true
        type: string

jobs:
  process:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Reusable Workflow
        uses: actions/checkout@v3
        with:
          repository: akvo/main-github-workflow
          path: main-github-workflow

      - name: Install gcloud-auth-plugin
        run: |
          REPO_URL="https://packages.cloud.google.com/apt"
          # Install the Google Cloud SDK
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo wget -q https://packages.cloud.google.com/apt/doc/apt-key.gpg -O /usr/share/keyrings/cloud.google.gpg
          sudo apt-get update -y
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
        shell: bash

      - name: Write secret to file
        run: echo "${{ secrets.GCLOUD_SERVICE_ACCOUNT }}" | base64 --decode > gcp.json
        shell: bash

      - name: Rollout
        run: ./main-github-workflow/helpers/general/rollout.sh  ${{ inputs.app-name }} ${{ inputs.service-name }}  $GITHUB_REF_NAME.$GITHUB_SHA
        shell: bash
