name: Yarn Operation

on:
  workflow_call:
    secrets:
      GCLOUD_SERVICE_ACCOUNT:
        required: true

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Resository
        uses: actions/checkout@v3

      - name: Checkout Reusable Workflow
        uses: actions/checkout@v3
        with:
          repository: akvo/main-github-workflow
          path: main-github-workflow

      - name: Yarn install and build
        run: ./main-github-workflow/helpers/node/yarn-operation.sh
        shell: bash

      - name: Yarn Artifact Upload
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: /build
          retention-days: 1
